name = "QuadPol"
uuid = "8fb4fc55-c324-4059-b5c4-a155b47617a4"
authors = ["Miles Lucas <mdlucas@hawaii.edu> and contributors"]
version = "0.1.0"

[deps]
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Measurements = "2.11.0"
Printf = "1.11.0"
julia = "1.11"
